---
jobs:
  tests:
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pipx install cpp-coveralls
          curl -s http://archive.neon.kde.org/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/neon-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/neon-archive-keyring.gpg] http://archive.neon.kde.org/user noble main" | sudo tee /etc/apt/sources.list.d/neon.list > /dev/null
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y libkf6texteditor-dev libkf6i18n-dev libkf6coreaddons-dev extra-cmake-modules lcov qt6-base-dev
      - name: Configure
        run: >-
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -B ${{github.workspace}}/build
          --install-prefix ${{github.workspace}}/build/prefix
      - name: Build
        run: cmake --build ${{github.workspace}}/build --verbose --config ${{matrix.build-type}}
      - name: Install
        run: cmake --install ${{github.workspace}}/build --config ${{matrix.build-type}} --verbose
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
name: Tests
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
